#!/bin/bash

echo "Enter first number:"
read num1

echo "Enter second number:"
read num2

sum=$((num1 + num2))

echo "Sum = $sum"



#!/bin/bash

echo "Enter first number:"
read num1

echo "Enter second number:"
read num2

result=$((num1 - num2))

echo "Result = $result"



#!/bin/bash

echo "Enter first number:"
read num1

echo "Enter second number:"
read num2

result=$((num1 * num2))

echo "Result = $result"



#!/bin/bash

echo "Enter first number:"
read num1

echo "Enter second number:"
read num2

if [ $num2 -eq 0 ]
then
  echo "Error: Division by zero is not allowed"
else
  result=$((num1 / num2))
  echo "Result = $result"
fi



#!/bin/bash

echo "Enter country name:"
read country

if [ "$country" = "india" ]
then
  echo "Country name is India"

elif [ "$country" = "nepal" ]
then
  echo "Country name is Nepal"

else
  echo "Not matching with India and Nepal"
fi



#!/bin/bash

echo "Enter your age:"
read age

if [ $age -eq 18 ]
then
  echo "Your age is 18"
else
  echo "Your age is not 18"
fi



#!/bin/bash

echo "Enter first number:"
read num1

echo "Enter second number:"
read num2

if [ $num1 -gt $num2 ]
then
  echo "$num1 is largest"
else
  echo "$num2 is largest"
fi



#!/bin/bash

echo "Enter first number:"
read a

echo "Enter second number:"
read b

echo "Enter third number:"
read c

if [ $a -gt $b ] && [ $a -gt $c ]
then
  echo "$a is largest"

elif [ $b -gt $a ] && [ $b -gt $c ]
then
  echo "$b is largest"

else
  echo "$c is largest"
fi



#!/bin/bash

echo "Enter a year:"
read year

if [ $((year % 400)) -eq 0 ]
then
  echo "$year is a Leap Year"

elif [ $((year % 100)) -eq 0 ]
then
  echo "$year is NOT a Leap Year"

elif [ $((year % 4)) -eq 0 ]
then
  echo "$year is a Leap Year"

else
  echo "$year is NOT a Leap Year"
fi



#!/bin/bash

echo "Enter marks:"
read marks

if [ $marks -ge 90 ]
then
  echo "Grade: A"

elif [ $marks -ge 75 ]
then
  echo "Grade: B"

elif [ $marks -ge 60 ]
then
  echo "Grade: C"

elif [ $marks -ge 40 ]
then
  echo "Grade: D"

else
  echo "Grade: F"
fi
